# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.vehicle_property_list_inner import VehiclePropertyListInner  # noqa: E501
from swagger_client.rest import ApiException


class TestVehiclePropertyListInner(unittest.TestCase):
    """VehiclePropertyListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVehiclePropertyListInner(self):
        """Test VehiclePropertyListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.vehicle_property_list_inner.VehiclePropertyListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
