# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.country_list import CountryList  # noqa: E501
from swagger_client.rest import ApiException


class TestCountryList(unittest.TestCase):
    """CountryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountryList(self):
        """Test CountryList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.country_list.CountryList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
