# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.user_group_list import UserGroupList  # noqa: E501
from swagger_client.rest import ApiException


class TestUserGroupList(unittest.TestCase):
    """UserGroupList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserGroupList(self):
        """Test UserGroupList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_group_list.UserGroupList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
