# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.update_notification_settings_notification import UpdateNotificationSettingsNotification  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateNotificationSettingsNotification(unittest.TestCase):
    """UpdateNotificationSettingsNotification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateNotificationSettingsNotification(self):
        """Test UpdateNotificationSettingsNotification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_notification_settings_notification.UpdateNotificationSettingsNotification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
