# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.alert_list_list import AlertListList  # noqa: E501
from swagger_client.rest import ApiException


class TestAlertListList(unittest.TestCase):
    """AlertListList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertListList(self):
        """Test AlertListList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.alert_list_list.AlertListList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
