# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.v2_api import V2Api  # noqa: E501
from swagger_client.rest import ApiException


class TestV2Api(unittest.TestCase):
    """V2Api unit test stubs"""

    def setUp(self):
        self.api = api.v2_api.V2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user_profile(self):
        """Test case for create_user_profile

        """
        pass

    def test_create_vehicle_category(self):
        """Test case for create_vehicle_category

        """
        pass

    def test_delete_user_profile(self):
        """Test case for delete_user_profile

        """
        pass

    def test_delete_vehicle_category(self):
        """Test case for delete_vehicle_category

        """
        pass

    def test_enable_vehicle_maintenance(self):
        """Test case for enable_vehicle_maintenance

        """
        pass

    def test_get_alert_list(self):
        """Test case for get_alert_list

        """
        pass

    def test_get_alerts_status(self):
        """Test case for get_alerts_status

        """
        pass

    def test_get_current_user_profile(self):
        """Test case for get_current_user_profile

        """
        pass

    def test_get_fleet_status(self):
        """Test case for get_fleet_status

        """
        pass

    def test_get_notification_settings(self):
        """Test case for get_notification_settings

        """
        pass

    def test_get_related_user_profiles(self):
        """Test case for get_related_user_profiles

        """
        pass

    def test_get_user_profile(self):
        """Test case for get_user_profile

        """
        pass

    def test_get_vehicle_category(self):
        """Test case for get_vehicle_category

        """
        pass

    def test_get_vehicle_category_list(self):
        """Test case for get_vehicle_category_list

        """
        pass

    def test_get_vehicle_status(self):
        """Test case for get_vehicle_status

        """
        pass

    def test_get_vehicles(self):
        """Test case for get_vehicles

        """
        pass

    def test_get_vehicles_daily_stats(self):
        """Test case for get_vehicles_daily_stats

        """
        pass

    def test_get_vehicles_frame_history(self):
        """Test case for get_vehicles_frame_history

        """
        pass

    def test_get_vehicles_refuels(self):
        """Test case for get_vehicles_refuels

        """
        pass

    def test_get_vehicles_stopped_consumptions(self):
        """Test case for get_vehicles_stopped_consumptions

        """
        pass

    def test_refresh_api_token(self):
        """Test case for refresh_api_token

        """
        pass

    def test_update_notification_settings(self):
        """Test case for update_notification_settings

        """
        pass

    def test_update_user_profile(self):
        """Test case for update_user_profile

        """
        pass

    def test_update_vehicle(self):
        """Test case for update_vehicle

        """
        pass

    def test_update_vehicle_category(self):
        """Test case for update_vehicle_category

        """
        pass


if __name__ == '__main__':
    unittest.main()
