# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.alert_list import AlertList  # noqa: E501
from swagger_client.rest import ApiException


class TestAlertList(unittest.TestCase):
    """AlertList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertList(self):
        """Test AlertList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.alert_list.AlertList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
