# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.vehicle_national_type_list_inner import VehicleNationalTypeListInner  # noqa: E501
from swagger_client.rest import ApiException


class TestVehicleNationalTypeListInner(unittest.TestCase):
    """VehicleNationalTypeListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVehicleNationalTypeListInner(self):
        """Test VehicleNationalTypeListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.vehicle_national_type_list_inner.VehicleNationalTypeListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
