# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.user_level import UserLevel  # noqa: E501
from swagger_client.rest import ApiException


class TestUserLevel(unittest.TestCase):
    """UserLevel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserLevel(self):
        """Test UserLevel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_level.UserLevel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
