# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.update_notification_settings_notification_alert1 import UpdateNotificationSettingsNotificationAlert1  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateNotificationSettingsNotificationAlert1(unittest.TestCase):
    """UpdateNotificationSettingsNotificationAlert1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateNotificationSettingsNotificationAlert1(self):
        """Test UpdateNotificationSettingsNotificationAlert1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_notification_settings_notification_alert1.UpdateNotificationSettingsNotificationAlert1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
