# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.user_profile_groups import UserProfileGroups  # noqa: E501
from swagger_client.rest import ApiException


class TestUserProfileGroups(unittest.TestCase):
    """UserProfileGroups unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserProfileGroups(self):
        """Test UserProfileGroups"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_profile_groups.UserProfileGroups()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
