# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.vehicle_technical import VehicleTechnical  # noqa: E501
from swagger_client.rest import ApiException


class TestVehicleTechnical(unittest.TestCase):
    """VehicleTechnical unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVehicleTechnical(self):
        """Test VehicleTechnical"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.vehicle_technical.VehicleTechnical()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
