# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.update_notification_settings_notification_alert3 import UpdateNotificationSettingsNotificationAlert3  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateNotificationSettingsNotificationAlert3(unittest.TestCase):
    """UpdateNotificationSettingsNotificationAlert3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateNotificationSettingsNotificationAlert3(self):
        """Test UpdateNotificationSettingsNotificationAlert3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_notification_settings_notification_alert3.UpdateNotificationSettingsNotificationAlert3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
