# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.alert_list_driver import AlertListDriver  # noqa: E501
from swagger_client.rest import ApiException


class TestAlertListDriver(unittest.TestCase):
    """AlertListDriver unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertListDriver(self):
        """Test AlertListDriver"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.alert_list_driver.AlertListDriver()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
