# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.user_authorization_api import UserAuthorizationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserAuthorizationApi(unittest.TestCase):
    """UserAuthorizationApi unit test stubs"""

    def setUp(self):
        self.api = api.user_authorization_api.UserAuthorizationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authorize(self):
        """Test case for authorize

        """
        pass


if __name__ == '__main__':
    unittest.main()
