# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.vehicle_list import VehicleList  # noqa: E501
from swagger_client.rest import ApiException


class TestVehicleList(unittest.TestCase):
    """VehicleList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVehicleList(self):
        """Test VehicleList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.vehicle_list.VehicleList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
