# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.user_profile_list_list import UserProfileListList  # noqa: E501
from swagger_client.rest import ApiException


class TestUserProfileListList(unittest.TestCase):
    """UserProfileListList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserProfileListList(self):
        """Test UserProfileListList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_profile_list_list.UserProfileListList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
