# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.update_notification_settings_notification_alert9 import UpdateNotificationSettingsNotificationAlert9  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateNotificationSettingsNotificationAlert9(unittest.TestCase):
    """UpdateNotificationSettingsNotificationAlert9 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateNotificationSettingsNotificationAlert9(self):
        """Test UpdateNotificationSettingsNotificationAlert9"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_notification_settings_notification_alert9.UpdateNotificationSettingsNotificationAlert9()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
