# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.vehicle_fuel_type_list import VehicleFuelTypeList  # noqa: E501
from swagger_client.rest import ApiException


class TestVehicleFuelTypeList(unittest.TestCase):
    """VehicleFuelTypeList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVehicleFuelTypeList(self):
        """Test VehicleFuelTypeList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.vehicle_fuel_type_list.VehicleFuelTypeList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
