# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.vehicle_daily_stats_desc import VehicleDailyStatsDesc  # noqa: E501
from swagger_client.rest import ApiException


class TestVehicleDailyStatsDesc(unittest.TestCase):
    """VehicleDailyStatsDesc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVehicleDailyStatsDesc(self):
        """Test VehicleDailyStatsDesc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.vehicle_daily_stats_desc.VehicleDailyStatsDesc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
