# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.alerts_status_desc import AlertsStatusDesc  # noqa: E501
from swagger_client.rest import ApiException


class TestAlertsStatusDesc(unittest.TestCase):
    """AlertsStatusDesc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertsStatusDesc(self):
        """Test AlertsStatusDesc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.alerts_status_desc.AlertsStatusDesc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
