# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.update_notification_settings import UpdateNotificationSettings  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateNotificationSettings(unittest.TestCase):
    """UpdateNotificationSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateNotificationSettings(self):
        """Test UpdateNotificationSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_notification_settings.UpdateNotificationSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
