# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.v1_api import V1Api  # noqa: E501
from swagger_client.rest import ApiException


class TestV1Api(unittest.TestCase):
    """V1Api unit test stubs"""

    def setUp(self):
        self.api = api.v1_api.V1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_countries_list(self):
        """Test case for get_countries_list

        """
        pass

    def test_get_tank_types_list(self):
        """Test case for get_tank_types_list

        """
        pass

    def test_get_vehicle_brand_list(self):
        """Test case for get_vehicle_brand_list

        """
        pass

    def test_get_vehicle_fuel_types_list(self):
        """Test case for get_vehicle_fuel_types_list

        """
        pass

    def test_get_vehicle_model_list(self):
        """Test case for get_vehicle_model_list

        """
        pass

    def test_get_vehicle_national_type_list(self):
        """Test case for get_vehicle_national_type_list

        """
        pass

    def test_get_vehicle_properties_list(self):
        """Test case for get_vehicle_properties_list

        """
        pass

    def test_get_vehicle_type_list(self):
        """Test case for get_vehicle_type_list

        """
        pass

    def test_get_vehicle_version_list(self):
        """Test case for get_vehicle_version_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
