# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AlertsStatusInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'frame_id': 'str',
        'sensor': 'object',
        'imei': 'str',
        'msg_time': 'int',
        'latitude': 'int',
        'longitude': 'int',
        'fuel_level': 'float',
        'vehicle_id': 'int',
        'driver_id': 'int',
        'is_maintenance_enabled': 'bool'
    }

    attribute_map = {
        'frame_id': 'frame_id',
        'sensor': 'sensor',
        'imei': 'imei',
        'msg_time': 'msg_time',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'fuel_level': 'fuel_level',
        'vehicle_id': 'vehicle_id',
        'driver_id': 'driver_id',
        'is_maintenance_enabled': 'is_maintenance_enabled'
    }

    def __init__(self, frame_id=None, sensor=None, imei=None, msg_time=None, latitude=None, longitude=None, fuel_level=None, vehicle_id=None, driver_id=None, is_maintenance_enabled=None):  # noqa: E501
        """AlertsStatusInner - a model defined in Swagger"""  # noqa: E501
        self._frame_id = None
        self._sensor = None
        self._imei = None
        self._msg_time = None
        self._latitude = None
        self._longitude = None
        self._fuel_level = None
        self._vehicle_id = None
        self._driver_id = None
        self._is_maintenance_enabled = None
        self.discriminator = None
        if frame_id is not None:
            self.frame_id = frame_id
        if sensor is not None:
            self.sensor = sensor
        if imei is not None:
            self.imei = imei
        if msg_time is not None:
            self.msg_time = msg_time
        if latitude is not None:
            self.latitude = latitude
        if longitude is not None:
            self.longitude = longitude
        if fuel_level is not None:
            self.fuel_level = fuel_level
        if vehicle_id is not None:
            self.vehicle_id = vehicle_id
        if driver_id is not None:
            self.driver_id = driver_id
        if is_maintenance_enabled is not None:
            self.is_maintenance_enabled = is_maintenance_enabled

    @property
    def frame_id(self):
        """Gets the frame_id of this AlertsStatusInner.  # noqa: E501


        :return: The frame_id of this AlertsStatusInner.  # noqa: E501
        :rtype: str
        """
        return self._frame_id

    @frame_id.setter
    def frame_id(self, frame_id):
        """Sets the frame_id of this AlertsStatusInner.


        :param frame_id: The frame_id of this AlertsStatusInner.  # noqa: E501
        :type: str
        """

        self._frame_id = frame_id

    @property
    def sensor(self):
        """Gets the sensor of this AlertsStatusInner.  # noqa: E501


        :return: The sensor of this AlertsStatusInner.  # noqa: E501
        :rtype: object
        """
        return self._sensor

    @sensor.setter
    def sensor(self, sensor):
        """Sets the sensor of this AlertsStatusInner.


        :param sensor: The sensor of this AlertsStatusInner.  # noqa: E501
        :type: object
        """

        self._sensor = sensor

    @property
    def imei(self):
        """Gets the imei of this AlertsStatusInner.  # noqa: E501


        :return: The imei of this AlertsStatusInner.  # noqa: E501
        :rtype: str
        """
        return self._imei

    @imei.setter
    def imei(self, imei):
        """Sets the imei of this AlertsStatusInner.


        :param imei: The imei of this AlertsStatusInner.  # noqa: E501
        :type: str
        """

        self._imei = imei

    @property
    def msg_time(self):
        """Gets the msg_time of this AlertsStatusInner.  # noqa: E501


        :return: The msg_time of this AlertsStatusInner.  # noqa: E501
        :rtype: int
        """
        return self._msg_time

    @msg_time.setter
    def msg_time(self, msg_time):
        """Sets the msg_time of this AlertsStatusInner.


        :param msg_time: The msg_time of this AlertsStatusInner.  # noqa: E501
        :type: int
        """

        self._msg_time = msg_time

    @property
    def latitude(self):
        """Gets the latitude of this AlertsStatusInner.  # noqa: E501


        :return: The latitude of this AlertsStatusInner.  # noqa: E501
        :rtype: int
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this AlertsStatusInner.


        :param latitude: The latitude of this AlertsStatusInner.  # noqa: E501
        :type: int
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this AlertsStatusInner.  # noqa: E501


        :return: The longitude of this AlertsStatusInner.  # noqa: E501
        :rtype: int
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this AlertsStatusInner.


        :param longitude: The longitude of this AlertsStatusInner.  # noqa: E501
        :type: int
        """

        self._longitude = longitude

    @property
    def fuel_level(self):
        """Gets the fuel_level of this AlertsStatusInner.  # noqa: E501


        :return: The fuel_level of this AlertsStatusInner.  # noqa: E501
        :rtype: float
        """
        return self._fuel_level

    @fuel_level.setter
    def fuel_level(self, fuel_level):
        """Sets the fuel_level of this AlertsStatusInner.


        :param fuel_level: The fuel_level of this AlertsStatusInner.  # noqa: E501
        :type: float
        """

        self._fuel_level = fuel_level

    @property
    def vehicle_id(self):
        """Gets the vehicle_id of this AlertsStatusInner.  # noqa: E501


        :return: The vehicle_id of this AlertsStatusInner.  # noqa: E501
        :rtype: int
        """
        return self._vehicle_id

    @vehicle_id.setter
    def vehicle_id(self, vehicle_id):
        """Sets the vehicle_id of this AlertsStatusInner.


        :param vehicle_id: The vehicle_id of this AlertsStatusInner.  # noqa: E501
        :type: int
        """

        self._vehicle_id = vehicle_id

    @property
    def driver_id(self):
        """Gets the driver_id of this AlertsStatusInner.  # noqa: E501


        :return: The driver_id of this AlertsStatusInner.  # noqa: E501
        :rtype: int
        """
        return self._driver_id

    @driver_id.setter
    def driver_id(self, driver_id):
        """Sets the driver_id of this AlertsStatusInner.


        :param driver_id: The driver_id of this AlertsStatusInner.  # noqa: E501
        :type: int
        """

        self._driver_id = driver_id

    @property
    def is_maintenance_enabled(self):
        """Gets the is_maintenance_enabled of this AlertsStatusInner.  # noqa: E501


        :return: The is_maintenance_enabled of this AlertsStatusInner.  # noqa: E501
        :rtype: bool
        """
        return self._is_maintenance_enabled

    @is_maintenance_enabled.setter
    def is_maintenance_enabled(self, is_maintenance_enabled):
        """Sets the is_maintenance_enabled of this AlertsStatusInner.


        :param is_maintenance_enabled: The is_maintenance_enabled of this AlertsStatusInner.  # noqa: E501
        :type: bool
        """

        self._is_maintenance_enabled = is_maintenance_enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AlertsStatusInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AlertsStatusInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
