# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class CreateVehicleCategory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vehicle_category_form': 'CreateVehicleCategoryVehicleCategoryForm'
    }

    attribute_map = {
        'vehicle_category_form': 'vehicle_category_form'
    }

    def __init__(self, vehicle_category_form=None):  # noqa: E501
        """CreateVehicleCategory - a model defined in Swagger"""  # noqa: E501
        self._vehicle_category_form = None
        self.discriminator = None
        if vehicle_category_form is not None:
            self.vehicle_category_form = vehicle_category_form

    @property
    def vehicle_category_form(self):
        """Gets the vehicle_category_form of this CreateVehicleCategory.  # noqa: E501


        :return: The vehicle_category_form of this CreateVehicleCategory.  # noqa: E501
        :rtype: CreateVehicleCategoryVehicleCategoryForm
        """
        return self._vehicle_category_form

    @vehicle_category_form.setter
    def vehicle_category_form(self, vehicle_category_form):
        """Sets the vehicle_category_form of this CreateVehicleCategory.


        :param vehicle_category_form: The vehicle_category_form of this CreateVehicleCategory.  # noqa: E501
        :type: CreateVehicleCategoryVehicleCategoryForm
        """

        self._vehicle_category_form = vehicle_category_form

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateVehicleCategory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateVehicleCategory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
