# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class StopppedConsumptionListList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'created_at': 'int',
        'longitude': 'str',
        'latitude': 'str',
        'finished_at': 'int'
    }

    attribute_map = {
        'id': 'id',
        'created_at': 'created_at',
        'longitude': 'longitude',
        'latitude': 'latitude',
        'finished_at': 'finished_at'
    }

    def __init__(self, id=None, created_at=None, longitude=None, latitude=None, finished_at=None):  # noqa: E501
        """StopppedConsumptionListList - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._created_at = None
        self._longitude = None
        self._latitude = None
        self._finished_at = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if created_at is not None:
            self.created_at = created_at
        if longitude is not None:
            self.longitude = longitude
        if latitude is not None:
            self.latitude = latitude
        if finished_at is not None:
            self.finished_at = finished_at

    @property
    def id(self):
        """Gets the id of this StopppedConsumptionListList.  # noqa: E501


        :return: The id of this StopppedConsumptionListList.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this StopppedConsumptionListList.


        :param id: The id of this StopppedConsumptionListList.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def created_at(self):
        """Gets the created_at of this StopppedConsumptionListList.  # noqa: E501


        :return: The created_at of this StopppedConsumptionListList.  # noqa: E501
        :rtype: int
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this StopppedConsumptionListList.


        :param created_at: The created_at of this StopppedConsumptionListList.  # noqa: E501
        :type: int
        """

        self._created_at = created_at

    @property
    def longitude(self):
        """Gets the longitude of this StopppedConsumptionListList.  # noqa: E501


        :return: The longitude of this StopppedConsumptionListList.  # noqa: E501
        :rtype: str
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this StopppedConsumptionListList.


        :param longitude: The longitude of this StopppedConsumptionListList.  # noqa: E501
        :type: str
        """

        self._longitude = longitude

    @property
    def latitude(self):
        """Gets the latitude of this StopppedConsumptionListList.  # noqa: E501


        :return: The latitude of this StopppedConsumptionListList.  # noqa: E501
        :rtype: str
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this StopppedConsumptionListList.


        :param latitude: The latitude of this StopppedConsumptionListList.  # noqa: E501
        :type: str
        """

        self._latitude = latitude

    @property
    def finished_at(self):
        """Gets the finished_at of this StopppedConsumptionListList.  # noqa: E501


        :return: The finished_at of this StopppedConsumptionListList.  # noqa: E501
        :rtype: int
        """
        return self._finished_at

    @finished_at.setter
    def finished_at(self, finished_at):
        """Sets the finished_at of this StopppedConsumptionListList.


        :param finished_at: The finished_at of this StopppedConsumptionListList.  # noqa: E501
        :type: int
        """

        self._finished_at = finished_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StopppedConsumptionListList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StopppedConsumptionListList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
