# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class UpdateProfileUser(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'firstname': 'str',
        'lastname': 'str',
        'email': 'str',
        'phone': 'str',
        'comment': 'str',
        'groups': 'list[int]',
        'company': 'str',
        'company_short_name': 'str',
        'notify_timezone': 'int',
        'lang': 'int',
        'nav_system_access_data': 'CreateProfileUserNavSystemAccessData'
    }

    attribute_map = {
        'firstname': 'firstname',
        'lastname': 'lastname',
        'email': 'email',
        'phone': 'phone',
        'comment': 'comment',
        'groups': 'groups',
        'company': 'company',
        'company_short_name': 'company_short_name',
        'notify_timezone': 'notify_timezone',
        'lang': 'lang',
        'nav_system_access_data': 'nav_system_access_data'
    }

    def __init__(self, firstname=None, lastname=None, email=None, phone=None, comment=None, groups=None, company=None, company_short_name=None, notify_timezone=None, lang=None, nav_system_access_data=None):  # noqa: E501
        """UpdateProfileUser - a model defined in Swagger"""  # noqa: E501
        self._firstname = None
        self._lastname = None
        self._email = None
        self._phone = None
        self._comment = None
        self._groups = None
        self._company = None
        self._company_short_name = None
        self._notify_timezone = None
        self._lang = None
        self._nav_system_access_data = None
        self.discriminator = None
        if firstname is not None:
            self.firstname = firstname
        if lastname is not None:
            self.lastname = lastname
        if email is not None:
            self.email = email
        if phone is not None:
            self.phone = phone
        if comment is not None:
            self.comment = comment
        if groups is not None:
            self.groups = groups
        if company is not None:
            self.company = company
        if company_short_name is not None:
            self.company_short_name = company_short_name
        if notify_timezone is not None:
            self.notify_timezone = notify_timezone
        if lang is not None:
            self.lang = lang
        if nav_system_access_data is not None:
            self.nav_system_access_data = nav_system_access_data

    @property
    def firstname(self):
        """Gets the firstname of this UpdateProfileUser.  # noqa: E501


        :return: The firstname of this UpdateProfileUser.  # noqa: E501
        :rtype: str
        """
        return self._firstname

    @firstname.setter
    def firstname(self, firstname):
        """Sets the firstname of this UpdateProfileUser.


        :param firstname: The firstname of this UpdateProfileUser.  # noqa: E501
        :type: str
        """

        self._firstname = firstname

    @property
    def lastname(self):
        """Gets the lastname of this UpdateProfileUser.  # noqa: E501


        :return: The lastname of this UpdateProfileUser.  # noqa: E501
        :rtype: str
        """
        return self._lastname

    @lastname.setter
    def lastname(self, lastname):
        """Sets the lastname of this UpdateProfileUser.


        :param lastname: The lastname of this UpdateProfileUser.  # noqa: E501
        :type: str
        """

        self._lastname = lastname

    @property
    def email(self):
        """Gets the email of this UpdateProfileUser.  # noqa: E501


        :return: The email of this UpdateProfileUser.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UpdateProfileUser.


        :param email: The email of this UpdateProfileUser.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def phone(self):
        """Gets the phone of this UpdateProfileUser.  # noqa: E501


        :return: The phone of this UpdateProfileUser.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this UpdateProfileUser.


        :param phone: The phone of this UpdateProfileUser.  # noqa: E501
        :type: str
        """

        self._phone = phone

    @property
    def comment(self):
        """Gets the comment of this UpdateProfileUser.  # noqa: E501


        :return: The comment of this UpdateProfileUser.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this UpdateProfileUser.


        :param comment: The comment of this UpdateProfileUser.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def groups(self):
        """Gets the groups of this UpdateProfileUser.  # noqa: E501


        :return: The groups of this UpdateProfileUser.  # noqa: E501
        :rtype: list[int]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this UpdateProfileUser.


        :param groups: The groups of this UpdateProfileUser.  # noqa: E501
        :type: list[int]
        """

        self._groups = groups

    @property
    def company(self):
        """Gets the company of this UpdateProfileUser.  # noqa: E501


        :return: The company of this UpdateProfileUser.  # noqa: E501
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this UpdateProfileUser.


        :param company: The company of this UpdateProfileUser.  # noqa: E501
        :type: str
        """

        self._company = company

    @property
    def company_short_name(self):
        """Gets the company_short_name of this UpdateProfileUser.  # noqa: E501


        :return: The company_short_name of this UpdateProfileUser.  # noqa: E501
        :rtype: str
        """
        return self._company_short_name

    @company_short_name.setter
    def company_short_name(self, company_short_name):
        """Sets the company_short_name of this UpdateProfileUser.


        :param company_short_name: The company_short_name of this UpdateProfileUser.  # noqa: E501
        :type: str
        """

        self._company_short_name = company_short_name

    @property
    def notify_timezone(self):
        """Gets the notify_timezone of this UpdateProfileUser.  # noqa: E501


        :return: The notify_timezone of this UpdateProfileUser.  # noqa: E501
        :rtype: int
        """
        return self._notify_timezone

    @notify_timezone.setter
    def notify_timezone(self, notify_timezone):
        """Sets the notify_timezone of this UpdateProfileUser.


        :param notify_timezone: The notify_timezone of this UpdateProfileUser.  # noqa: E501
        :type: int
        """

        self._notify_timezone = notify_timezone

    @property
    def lang(self):
        """Gets the lang of this UpdateProfileUser.  # noqa: E501


        :return: The lang of this UpdateProfileUser.  # noqa: E501
        :rtype: int
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this UpdateProfileUser.


        :param lang: The lang of this UpdateProfileUser.  # noqa: E501
        :type: int
        """

        self._lang = lang

    @property
    def nav_system_access_data(self):
        """Gets the nav_system_access_data of this UpdateProfileUser.  # noqa: E501


        :return: The nav_system_access_data of this UpdateProfileUser.  # noqa: E501
        :rtype: CreateProfileUserNavSystemAccessData
        """
        return self._nav_system_access_data

    @nav_system_access_data.setter
    def nav_system_access_data(self, nav_system_access_data):
        """Sets the nav_system_access_data of this UpdateProfileUser.


        :param nav_system_access_data: The nav_system_access_data of this UpdateProfileUser.  # noqa: E501
        :type: CreateProfileUserNavSystemAccessData
        """

        self._nav_system_access_data = nav_system_access_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateProfileUser, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateProfileUser):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
