# coding: utf-8

"""
    Gkeep API

    Gkeep API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class VehicleTankPosition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'positions': 'list[str]',
        'system_name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'positions': 'positions',
        'system_name': 'system_name'
    }

    def __init__(self, id=None, name=None, positions=None, system_name=None):  # noqa: E501
        """VehicleTankPosition - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._positions = None
        self._system_name = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if positions is not None:
            self.positions = positions
        if system_name is not None:
            self.system_name = system_name

    @property
    def id(self):
        """Gets the id of this VehicleTankPosition.  # noqa: E501


        :return: The id of this VehicleTankPosition.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this VehicleTankPosition.


        :param id: The id of this VehicleTankPosition.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this VehicleTankPosition.  # noqa: E501


        :return: The name of this VehicleTankPosition.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VehicleTankPosition.


        :param name: The name of this VehicleTankPosition.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def positions(self):
        """Gets the positions of this VehicleTankPosition.  # noqa: E501


        :return: The positions of this VehicleTankPosition.  # noqa: E501
        :rtype: list[str]
        """
        return self._positions

    @positions.setter
    def positions(self, positions):
        """Sets the positions of this VehicleTankPosition.


        :param positions: The positions of this VehicleTankPosition.  # noqa: E501
        :type: list[str]
        """

        self._positions = positions

    @property
    def system_name(self):
        """Gets the system_name of this VehicleTankPosition.  # noqa: E501


        :return: The system_name of this VehicleTankPosition.  # noqa: E501
        :rtype: str
        """
        return self._system_name

    @system_name.setter
    def system_name(self, system_name):
        """Sets the system_name of this VehicleTankPosition.


        :param system_name: The system_name of this VehicleTankPosition.  # noqa: E501
        :type: str
        """

        self._system_name = system_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VehicleTankPosition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VehicleTankPosition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
